---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-heartbeat
  namespace: sa-p8-staging
spec:
  encryptedData:
    DB_PASSWORD: AgCG/GgaiYnACdOlgMZK2EFx8lXSJ6t4kQFOZpS/svLFj9/ErpbQVhShsriZ9/i3Y3XJ7IPsYMQVAo2jeP2NAlAzuXA/ihecbqVt0CXLn4478UBb0HCTxN11mSEywrrpzAro8h6opMnxJh9vNcWLVkNEThB0wyA7Lf1tNfkHT1yvCA01ha51+FnwqbsnHUIWOXTE/Q/YxJgRH2kHAbIM6qvY/7u525HkPKCNbdr3766pnHjQh7nggCmgH81jJOmLn2kg9M7TrHp6t5V4pCcS+oLLQJAHKvyBsee4SU7/TdvUMe1gtTu5xqoYW6CGTRr3ecjSUZxr9CB4Ini/QLrrLBa9PsOmpjNokdjEi1zNzepPNsDoJ7KJZg+t9OV7BgjndfXkJdDnc0bogA4AvMnyZ7bF05pmpztugNOGqSMDPFwMa4SEdKBD55Fd/ZRPiM42XJrVhrPLIV+NaM8cNWw2NlHTVhu6UjbdHsoSrrv4hh/FyfPY20OmRPg/kYMRTK+sNYvjB1w6+6d4mpwTyXOZpExWW9afxU2bIH76Yt0J/pkez/QYjj8OjhpS0GmqPpF3Jf30H13rdAwXA49KnmaXr8J5F/qIakSoq1+cFAlfkdbWSLzk/nZzpLTj3VHoCn0k6/FISSX+keKDZxMHIeJUvj1AhovW5cSumffTeVS6WFHNJK+b5yvVvu1g9Y/SM7wfN1Ofmph3BkMqBvdCDnHB8KHPUgCM4Kf1S1u5oAnXA/hUVg==
    DB_USER: AgCb5dy+T5UI4rDvtmY/JZcB55kwEF3I2lUEmReLrf/yaj2Qyu+sOmyiMSGUtfF289gTy3IAah9QEl4pRZ4W+uH3iSnb0xqQc15q1pLG4qInys+Az8ESaBWk+qeCz2TSlAziHSXUjBZy+oNGM0ADf4UawFk8yR/f+jJZE6Od7GFiCl60xY1z73eFBfzW5Qf+JfY1NdMUBjJ2Gqi6Wb/fgpUUdMpT1A7bvQktZLVFnJJIJGgJv7/f04V0S+EJCr1mhbH/F3Y3R85CEEvorfrUID+F2VTXL2ylJVQVkmb0ts3ob0yk2tWPwbAQ5oNevVvIeZtb9GGsJ2lC+sZenJx9t9jdWNNAmHc6e7xdqbh6PJq6iwdnLtA8veHx5zXVH7HgxJEiTrd/h7yERTTCYAtxDwqC2u6H+EJtFC/DH9fttfp0dBY/O25eiZ1hEGN8dK2my+r3YiNTwOhKmC6ToNGtdEwjJp8uk4626mISua23uAO0w7OClN3wuUTQArBxloLAwgg1FPX0uAD2lVTWa0shrapoPgnFgO5EdX4ZbgClbJHmol4aikEHYH+Oz63jfwGmIhoTd3EkafGXaP0qIMSCadB2nDsHNu3qJ6/0so+RE8cuxzIRc9jxWoc1rcXyfVrH8JSPpzWBYcfkkcZJ+/hTsBZEaVZWZA0JQ8GinkmFiUMFUSwZ84WQ/oWP4kTqgIj9eXXpGCap2OA=
  template:
    metadata:
      name: cronjob-heartbeat
      namespace: sa-p8-staging
