---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-heartbeat
  namespace: sa-p8-staging
spec:
  encryptedData:
    DB_PASSWORD: AgCjRYCU7G6Tr77zqDgxNfAMUJNmCwsX04NtaGGLTMLM1/nLx24o//O7STc32LJzed+eX9Iu6NLwHMyAA+BO6fl0m1zSMfQ0eTIKiGsLZua1rfYRe+yb9YeKTFLgcVsL7dWyl6LXJDamDokzb5QtFTjY9pPQ0V8BNBJCr5I0gWAZM6QgsaNLtO1S0Ef78NUvmspx966T0p1tUp/KzZnGlA8j8Ck/ClnPpgbX+rewY2PMUJ8lhhlbjVCF50YqFLx/dlE2VabpzilwjkuZ4RR+8pCXFOhI0GcMhFtxy3DAQGlx+LHGaRP298Y9WNKXeO589YjwYJmWRGbFkqVRFlC4wrOKuBzw3MCROpLc/PB2VK9eoAlf3zRgzrED5aEHMw1U2QR4KVucS6ZpeN+feyDkaHSCK4O6in1xsbiMszuKaamMzVgcoeWvGAoyYGG3miriUn124/4qWRm1Ptlur1MXtjrVMDOEO1DFidlAFPFsuxtpz+NNtzJkhsPpfI6EFjmtRDJ65PeQGDDk7t6gmud2zn63bC8rZUKkENQ6FNE9xC9srQJsCT9RCiE6EgxI7iCavF/iGVW+0vuenwiakWsk7dt/EzHqxByDIWbwl5HZqWTn6EyPoMy3u1JPCGh2hGlXWEU0QvXTdIe/x2OjBzQnxpKcpDQNEPzcQO7h8Ane4VjVpDMHYA8/I8qwmvdLv8o6aFk/nMVUbKygbzMIJP7BQTQnubf21c985YXS/Riu2KREfg==
    DB_USER: AgCAlD60XP2jAcqyak2a7eQ/x3ih8Dosrqnq11Bsxkg+j7YB9cRjD6Flwig9XYg7ekRl9tSk55EUQYW9U1dyvR5cw7eTQ3CZBcl208sclrC9dIP7TxUmo6ZwbftnIZiVTaOXTjN4pkV1bP4SnAKq6eumfpOGiz6cQPlKspp0DHqjS/4urJwIbzz8s7KHqqp7pPVsrmp4DzUYYyRbzKEk92cBjihb62SRU+sddoInexqnPEMbemZ+kMzz4UyI/jg3acyVJUBEUaETvPEssdhgmacxc62POIds8uvpGc2EarRi68+gXSmXtwTQBlolQHVL/1qigCZtt/6XuNcK7utKm68HFaNkX7DTBpN0t/Rh4wvfcnMmftGmL1m5pzu0ouOBDeN1rahzvCinTlZ4Qc8mSJYlQMa5e/LWsRfoM/mw0P4DXmzk/3ssS/VA/g6IStD2eToT0f0s16syT3RUgVjF3Hm4IAeBOuRibuBKVDjnz50SpLDlLnM4HvO/V6z85OBhE3ll5QuNKSxHxtNstu3wxAd9J12zyhVRBKp6efSb5BAgG2UCWDpGJOh4nV8q6EqVbAWBdUNaTbs0IHmYCv/OUHggvP8Wf/VcZFlacjfjBI1ZUBduP4020uCa0uA6cF8J1lkyTRGRBk0Bart4v4x3ss1/dIzWOO2H2pcKdsj97jJDiklH5AZyl27pi4sPmq7/5ooShAHTGts=
  template:
    metadata:
      name: cronjob-heartbeat
      namespace: sa-p8-staging
