---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-resumen
  namespace: sa-p8-staging
spec:
  encryptedData:
    DB_PASSWORD: AgBqGK/kGJuk3uDxbPQ0oopaBhXc0zHuXCGmdW36wHFNtSnbi1JTwWTrARXSi5fkcRiU+PumnUkL7TDAehGmKI4v7JyajyuCjM3pQK3Jo3q81RUIQlPBKarwfeEMZsURBQ1xLvqScJ6RVBnFFlBXK6KpqfdFBX7lFb6ZivoRcZZNbedCpaMITna41zz6ZfQevAM1yJ0vPrD7dfJbk8X7dA+pl6NqdXtxR6u9asElDc08z97mPoyOhbH8t7WShuqeyfQHL92ChBcEUPHnvbp920ET6Lr/I0o0OSoXkmQg5zr38MHlUILksyJDard7gMAuNWvbgybRBQmKQhcaoV2vnHUMcup3Y+6YL4Iy91HkrsMgblW5UJ+zaZQ4Enmfuz+tGFljffIlYfgc4Hd0EeoCel51O7LY3a5NrIR0XgxOiMbpVvLSIOhCGbWAjxdjoL3IuAH36aPk889LkUM5xbeLD0qXRRC6gnIhPp4vC17DVUr8ut0q75ywcDJjrFGqsvVdgjSqP/5PaQPxysQzmWxHOR3Qvr+MwSHP7XLGQxWucBvoGhE6t1iyPR0jdh7haa5IZc1DfpGX9AtHLhxoSURRs1Rjza96Q3MAu0T+4DtTN2UEBKPMWm3/UzEGF82XE/paO5SVLPr7ugxCxIxoAJmc9SxaRpWaPI2PTwSOSXvEwkZOwCyfs96rkXiRUeuhWtRCsSIheMr6f9Upyb9lmQQ4sm4bChjGAXQTmnUPvW3SgAylmA==
    DB_USER: AgAclgw3HPJDtgbYcChQDOYa7elbs4JI5EBh6z+uz9Dusbp7QZ/B5v/Dqge/ula/ajhk7ZvhiDEPo70VwtGJK2i7+BdHRRWkU92wrtuJ4zzHZsLIsmtprmVoM7NCeSq4RyTugm9yoI18Mt7gHJaY3UMWVh59jKo5DovbQ0+/uESj/1z7erT5D2lVHGQ5m1RvYVFQJ5DGjZ6ntg7q4JHXaibrHnUBydAJzsX5JaXasr6ue82hKi5QjBmEUyqtkPuxJ20+ciMpHEA+rpmmBuU/+AixEPVBtSCCBt6Y7JFx89izoalbDr36rHwRrPaa6QdtMFQbjbwkuZg0AMdW2yihxtow6hKvMHJ5sKB544zdNncSo6dQv/1X1uvwygnaO/4GuRrJAK+I7Ucwof+TFu6u0A11tR/OkOjmeJ82RpNQjZRZpxwfcKKy0feYLgEiJbZDxXAxwTlEcDMq8LXaxdgk7+cghBRnFrrZtyjwsaNLq2A7MA+yzTb9WerXPFbFUm5bEzIdQ5vlSorp3ElmTwWDdZ24ahit1E/7M/fqDxEML0PsdK95BfzIA2v6O/aYipm6QgGPzeM5bvvQqs5TwNg50/B8C33036/hZ8Rms5cDXawmO6r35TTTYJ0WrFolT4kPA0QYwlLBkqJDNQ0IkGRYalYknqhcIWWwZHuTnE++2YxVzRJzqKfCVNXGlXsH339j5hcEF0FmUg8=
  template:
    metadata:
      name: cronjob-resumen
      namespace: sa-p8-staging
