---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-resumen
  namespace: sa-p8-staging
spec:
  encryptedData:
    DB_PASSWORD: AgAnasV+LeZ/U9xbjX2v1yFhvVZ/BW9x9vPYwg3rJb9SeKU5ZRQYiS+5tdo2SSUTkHNHF1wHjhNnkHMWP1zKRMxbWRnX26ypLh4CCcp2ex53HkXEA77MznYKtHtUaDzcFvfzUKBxvyy9Dp1zSMiv/0D1CMut8VQZYxFzxsj0RmkXxsX+/Yd5N5S3v8LjalLsxpYbU2SBpk1lb+N2fGcbYIOdXFspn3GiBekUGwhXVG7LjCKSUrlReCQOyNxcYZD82mVIVAS6tZftonBwQjtGGM7Sy6BMI+If4lvHj4LuBk2bKm2sIzwWYaLHSZFEVcow9TFll+JRCk9OF8G1XCbvFIe6bRvKzGN+cmKskfZYm7Jyiuxba4KP0FXg+YySgmyQiT6br9lkC/H98+OghXP97WkYI60/uDHhvHB8cq5sF6ArE1tNZz1vqZMjofbbZI/MMLe0qhJmwAw6uwtm5X9nfkzxKiDf+rJjtP/SSCUGASZ9rQ9H00k69K3Zln5fbQv44E7D2O7u3S3Il6iMDdcfIcaVWz3YW5BWcMhiSva2y80hgArdgwqTK1KI574APG7efgjJqReeO6PlPMGC1pCdynPol3pObpusqzRcp2jGA3NwJ+spUxECsV7hfGNxU0f9PG65T1HCypwPsvqrXyo1wm8FVZ1sFTUpxO9hSs2rfzLY5zSYabjpBBI8Uno9JeuNnQLmlNeRi/pxGoJ4nDRAiMFNxf4uJw55p4xYAeuQ8UGSVg==
    DB_USER: AgBIzt5NgZew9bcMbplmTn6XpRZpYScTIHk5HM0ETCGrO57yRcJY4sldTpTPrzpLDihoPtuxXBtPQ+sh6iZXhE05p764S0twBzsbV9rpT5XHmyo+73GXNLZ0EJ9OGazPgd8t2j2EXmRRhIH+jqxHtFl9x+VXjEJ5C011wiPFkQFfnXcRUrWZ3jdSn+lMi0pSQ20N1bqvjCV783xx+FG+7VoFW6JotefUrECFglkbfDAq6c/8GrG9A5GckdUZ7cpHZePvNgnllZ7ucZYDnlsklscIlqItOD2QIsUoY33NgsAfoz9GYxVkArudmpjmIL3IdNICfng9f9nW3zi64/jhRwkWXTsoaBAiyYHTX4qWnSbMvgSsvtrl2lynvIU026QpUHufobpx+y4mIVsXtZ2qt5tThsqCKvj8eCglsRwlVEIV+aleH66xJ/kGFSc+WIv9Ars3A+exnGYd8hSXB5JYqGmzNz/FVbhEqLgvA7lUl8CL5RJLX3nlbvUK3Y+o9sxBzHk3Gbxenp9NseWZuojgXacy5b7VaOSgIkBKH8zeFkoZWjl2yyQzl38MnpR62/H9cPfIs3Q30wUvQUDZMEUPb0kv+NNKVLGgosqEwFtnNy021oQS58gdmovYWToRlZLyyrHD44bT0i8wQ3XTfp1kMcAWnhRy/N/i1QB4gXHzrtU3I8NXq269RWIIiJ4PWlfnxmj/lmnSokE=
  template:
    metadata:
      name: cronjob-resumen
      namespace: sa-p8-staging
