---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: sa-p8-staging
spec:
  encryptedData:
    password: AgCT/euL21Hj/kw7qgE2LXgnRtszgMgEGu5Nbl1/YmJE24zglaloFbOWbtLnsJmawJFgslXtYRaw4dx4TjhYlDxPvKYqh/+kLpezAevzsHIp55i77V6yexjd5F1CrfRmLmpIFaifbt2VWSG7cBW87vRYpj2o77NS9batUBRBzPmiYt9tmHSDmIejRQhKdSe15Dw9biYoUn0oO0qxlo4OQNIaBnVygPDNvnqfZStv5aWBGKy0xy5WOBKp2TAND9nuwHgC26e8umNXLt3d/3PGgTWakaFvYgCMOJUIqn0333Kgk3sX4wPYlrhYxTjK1cSaxrZs7ldbtqQxTnARRpV3ryzTyv4ZrBbE30FNjWZCd7iIbakLdZUVgP2TJQO1zjZTIj+5uvlDiwFkBnJzwojYmcSMslhED8mBM+w32FhLTIvjtiNR6jZFnPf6tPfzkQufrZivdjbi8oGumh6kyuTYFFdHGsRCIkFAgw0GaXq0FFet+SpbkDZV4UqKNQA/jzJPNR1YFZRVNXepekjViLpn4oVQH8Ix2NoKiyp5khsN2nz7er3ZHA7oNKeV/a4/LjgoGZS6/+bIvQhZk7PsVooBukOmMpT0+PfUP9BLcKAGmetvrwIv2E3Ipj17AB/q/fEmylq/fIFuiT2A9wzpw7pgF42hbNxgFUIukrgM7/WuGNELy1puzSbLB+yVcGokRcVzGUJZGA9aa/UphoTdze/cqOfi1hPjXjq8Uaf18m67YJTqxw==
    postgres-password: AgBBQiyuzZTWtCQLYiP6sLAuQ3x5ppN+bPCYcoF+CwK1kmPr7PUBSytujZ6+ZIaFS/lzsO25RjKE6BNXrpoPbBa0Ib4lqLL6MWv/0gB99QF+YP1z8TKhId/46CZ1BbHiLinyHZSdTxkmyEsvD9vTCfIoI0XuFe5YBNcz0FZrRHZr0NSX2IdNyMs77Ww8hGRCI0ukSTj+pi1ChFToJ0s6GUpuelhWCl2zdP5uSQS8AQ0pJad4i9YD9wLUzKG5y1obJGQYrzSwwPdHvbt87zMgD/t2gnnh6xwoJA1QGKu5U8Mk3Vf/UBWtHpgcWJxjG7WB0b4E2f88vS0S1Z014irl6E0ceKaNs4fUnErbQS+jakHrilYQGTAf4qDmIwPYqW49I4WgEGW2UZQy29WBfqJETrwToI0gTiwwx1f8baGcA60SLJHvr51raa3irKZYqm2dpl34OWEJgUIF+czNE08La6/riUkt/W+7L0c9AYB6ybG1cDKFjCmRf+cpbgIcIQ/9c6gBjMI5ud5i3qph+xFnW+40PoHu1qO2XJL8x2xvTdSjO3pywWjwfp8jVvsEAOs47YxyedA10+YNKLt46Yr8GZErFCtGhuTBnSkFmYQNNJDlib2CTnlXWBs1/jKHOcmqUjcurlQ7JWaiBn0OHWYdCSoeq9P1OCwOCBoqoRY7mGvU0EgbtJYdX6S/QE6dCrRAmRlhmJcuBq1aLftNbVyIfMC/1stRP21A+TkefWenAqyctQ==
  template:
    metadata:
      name: postgres-auth
      namespace: sa-p8-staging
