---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: sa-p8-staging
spec:
  encryptedData:
    password: AgCWBAm5w8MQxPneRB73l95NH8AWc+/ZwLunYyyshgk8q8i52KXL8VTzGHfHOLC1UALerXhmpsGaFNAuQCC5d5LgMsQ9lsSZB4cO4Hj6HeHzEw3Anl5HnRIm8ojI0oDtA6EZep28Bk3jxs1X9l1pLXh0XRaApkYE2qnMh1Qem1m8jzPp7/cWJNaSBS0hh9fiY4lDyzP9Tz/b3h6N9c1/XT/PeExRvGzokdhkPyXI5zo03AjH2jSiVLAM2J4Q9H1xbZtgOUT+cWCTgXwsrRnExNBj8kVTHRp0lUCcWxrNbRFjv4+T3kVn0VoQ+hkdCvcQJ9XbTlsm8eE6jJfLQK7Tz+pUvuq6rIM4xKR0fgODWaVwgBaCTNAwMCy5qvqhbEyKxuoFkvfsBVXgDi616ZNzGyKqxJH2cvLGDHhQG0HLBmAWo9d7G7ssbMJdi/Xc/2bPp1f5Q8FoEyK2bF98AAZDBipU+YM651nV/Q78F0K8D3G5i63eTClNuVAs0+5SqI1GXX6hHuxq0lWzYRJ5EiRelpBjjYKBOm3iZUtJfK48kGzFwM9Uz8ncs1zVQB3kY4X7MhnHSQQb4BDYgu6aajAY0YkXIchZG64Bl3aARiREan8X5ZlDdXZxpjimetPoeCiDb/tXlKjp6dhp/SxXsBJ/UQSUdzDT9lSB+fAd7TLHKgJOEvNSky8r3iRXdv3xj4jXjT/2uFnOf/iUW5tuTRIrOcMw9mQYbF9/Qt2mU1njspUFMg==
    postgres-password: AgAU8hril2zrLLY9qeos0dC+5g+YieDVGt5ET9foIwOk01JdKpj9Hke2uYu7lcU3Tizt8aTa6PQDfiWrMQEkQOMz0IaQJjuiiywYTJ8y11n6QRoJwnI9/96zd8fVLizNcKFRRXHC2mV5Mv1Frst5G6MLVqiEUUl7OeFaHko4uPpXliH/a6BiyhG0TCfu+oOXKdn9LByWCD8dj3aqv/N+fTSG5vJMuzuOXZje6incBj7Wg4nrQ0Hwlvyroj4rR8+iZ30ZE/itWkbnqEo7FaeNRNCXCK5e/b+1lfECOoI8NGjyN70SDJFaNqymPPcIGdt/LF9zc77ZSVd+zW0uCfP8uaeWtKBlbE2jD+0tfVp/I7HIUm133tJVXONSwZemAg91Vg2RqW177T7NdQBrmFcJsdf32LnZmlIy2daYZH3tEY/k5hVwrN0tlZqVGS9CE5rkiyCsj1pPiGX18Ft6UOus9fyC+NFvize3mxU8BBpDnz/D8KNqZ1Quzm6aYfQjU82dyBnOq5TBcBHSundHuLmAx+HxW+6ESWVHXODrqcdhxyYVfDGzNqoP7zMTtUa7zErhvL2uHUUm9rn64LmdCYjLJ7xXoZVgvdUTdqpsoFbS40ifWmBqf7g4XrRhmU5H0FIY6hE4luKpuboYU47x5DvJFNPah3yV3SbfMD3BnDOKwqOT4YVPBl7tAG3d80VBucb9xsbSOPWEsg8HYC3kjSJN5raPJFxlUZ2RRhNLVUlHpLtA7Q==
  template:
    metadata:
      name: postgres-auth
      namespace: sa-p8-staging
