---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-heartbeat
  namespace: sa-p8-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCtDRDYLmHaYOOZfznYkVLIcxM+u0qXTOttKHpa4EfyS0Ojmm1kdUB1CABom9JPrR+JO06iSdUsbYIWZlVoSJjYJhnsWuJWFhd86ZG+xYFMFVbKtCjmExct9NcnA6qnGarnSK1JSVX6AdBqBsdVon5mB4sfm0144BsXKLWGYrEjDUCWjUFCTGYIUx9Q4CQ1M7zzuTh4aqqm1922v+dK8of0JT/+mfRXjMYi6P0xxiOJz3u+8/rRkk70yyK27O4Wr6gyfw0zeB5u8EBHNy+Al3k3ICBoPzfo/IcY99bkJ02hnBFVT6SS5lj7arpwvCk0FKprvMiWSDNKDNNVElvwm8MBgqkgb9lZniiLqfnIbQ1YqXCXwVGjjhyyOcJVHn017y4tp3d21YDJSpR/c/+wP74lnqNwnR1OoDOgD8axk8AQvmrXWLUPuuV/LW/cpj3p5WenBc3zBerqm9d9DNut9h1kyTRTnTMOcSm2rA5KMG4wrl/INoHcOLxkHTlO6jn/xrT4U82rCkCTafoh4nnTaiCCwdLyiaNZ4NE8GtzFPyfC8B/Kf+NC4OK4N9e1EBGTcd399iXEOuWZ/AxbKB60wLcce12b+e+fluCdewHv7KS5jzuBORfrTKfIKGL9XS01AucbLnpKUkGwDe5MR5BoAcr5vtliVXj727X2tVXw1LMjtJ8BfIhL73Ggoo5lVit5z96j5HtnAOiV2DEqZs+OjU0XiN+KEdNScEYQrrzhxpFO0w==
    DB_USER: AgBBJoIU+nMEH11ahiSTfvXGjYO7D1tKeZH+XLdZamM/RZMZw0Z7yULPPpAvoqBbonJt4qIPuTN1PUHg52tCk+L65II0DhG6OvFaHBKiyBiXc4wXkogUlEOZtIRprpu2JZbv0ZChfDP9WD51Mp/wEQ9YCkOvQ7grAbXLGLR3HjIyUkYhW1Xxa5PSuWv1SDk8sIgOcPDGHz7N+QgYDFhnaeW686fxIdGj/MOBg5nXGTONgZKmXOLSBwu+TfZJk+sfS0mSeuQ/iwwdip+lwgr+VQX56qKUPUE4Ta4YSQkd06MwenmCaI8ryJ1MfYHBODkT0O73ZJZf41lkQ+ISfAgW73cH6PjrU5PCXEE/Jhib/AXeXkJGvyq4TkEu9/ZD6s+wNmfMUG3ayUellEOh1v9wt17lFmsrXR7+IuLR7VAndd3xakyqylNzv6EcSkH9rGJQI+XhtnNWZXQnI67YDCJoc2tDhpLtb77foMDiqq6ND0jGVbgYTdMimVwYbjhjHjSGtMee2XnB3/X0iyw2VJPOHgreJWEAoRsy+ePQKbCWqEanIKFLq8QZ8QiGjCkcEmRNWDM9/jDrXMuA0wTYlB/dhT9bC2IjId86fWHaahyp8SDVIZFHGwQDVxhAS0yVLA5tYkZqe5jjOILUEdg664KEVxmjqx9N5/O/45vPwKVWzRPwNTKmidLqYGYYW672zoG/6/YAjBvXEY0=
  template:
    metadata:
      name: cronjob-heartbeat
      namespace: sa-p8-prod
