---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-resumen
  namespace: sa-p8-prod
spec:
  encryptedData:
    DB_PASSWORD: AgB3AKcBZaVdWngvgAGfx0BW8FfaKoHgYjdf5ML2n/msvIzAV7ORIziwAX1+r82Vv2C6bY1nLwjGBTRfZF6VlcusrAM1rQ8q+0esEtXZAGiIXyCt0HRa1M54Zbtm8iULP4SwQRwgHNhQJZXIJv7l7xtd0UXRoeCFznykpnDam9AL6GuCMgaYInM0KMDK/yXfreYkZm+TMYqot6q0nIAWXZY3fHk2DM9wF517T4DiBoIEtwlnAAOyJlU5jHcTY2S+Js7tNVNxSvJnmiUwT7vQoXFVOfaX2spdsW3pWTo/f8A4CJIj3TsHPzfG4+VEsXg3b6tGpAglGBX3Q/wEyivjcyrOijbmp3+2VSZSh/DAWMv8G+pOYA7NjFMswStP3TOF6pyU8mY3TlIxFupvjGe2KC7n0riSNjpYmOALraJgWmkjLD3GPOL8wBov8N8tV1QsdGjfATLLdu42RxWrTOVh/3pxXUdn2MU3BrrCcAplRYVm0DBCmaWCQ3V9Oag4YDABnCnHT3vZlmG8I0PoZyqP/IlsbOxLd53Ek5uC0o1sBxzroKLiwAweyWKYX8oAI8xzX9n1OOGZ90TD4SZlQG3GnVs6bjU8Z6+hi//EaBmhaLvPalBIYNl7ykoqzQgke6gVQT3u72KeTbBI7G4JztO/K+lCmGQEromR/grEncB2UbkTEP4qNQb+a4Em1jU4Z7rJplPD7rROvkFvIvJSfhvKDqJpQ1y9phK15H25blbMR2Cjhw==
    DB_USER: AgArnfJl2p3jqbrNSwPwrENY8tFqrFXK6j/G3hxReOZNZW9hm64V4T22aT86DzqqAHhra/gjMkFpBPPvSMqF+O2NTzQhtRGp0LoNxrL8+jxSiBiv1BPLzPwvfruuuG+x71Z8EcbvD+guJnr5V/2HaiwgvY+bJRjpzy4ARO2dgbc5otfIMNeQT0WUbVNJVfHryzJzGQweClmRsnSOCv5pcsDkPbQW739zeZeev3Npb5WCSOGxu3Lja5asUHWgSZrf8seeFucujl9f1Kxxl8Z5snbzb4CN/mooVa6y1wrs11I0oh3auupmSGchgaR3hpFX7NjprA695pFL9M8CJ7YM+h1UD0iLqLcZNuhsLeuD1bU2GZ9ombqEmDi8ZpW4gv5cPQTsdVNRB5M3FioLPxggsUactPKFOFMKRyE2wivIjzHcZretucmnwz3OujrccZCNvUmI/TwlKMS9uD1Q2Pv3veArveSDDonoawaKmVKjCVXDP34hB0Iaf0SbwTNu6mqW1Y3m2/u0Mke/bgQgzCcFvTathQui3eqF7sBg7IYs3kuoonCwWLEKQE5ZwK1yv5QO3EmoszVDQO9cKXMPmzitSiMG2MkyK+AsqKp9mN4JRdII9kdkoiz+KWYfkHjLJ1BqgenxVfAcVT4wrTHpnwFNDkZrSzCv7hIGJhhNJinEGqhDsEpaSjWOZWjacJlAiMosjHxZn8BVAN4=
  template:
    metadata:
      name: cronjob-resumen
      namespace: sa-p8-prod
