---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-resumen
  namespace: sa-p8-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBMiBh48NCgagntAu5oHmrlKerTJR9vb+sRYZ/vu8Ea775c6WDSVv0GlXtqPQE75+rbNjLZTRyQWolg//6LX0515MVxgiFBVNXkm4+XbicgLiRL3JLKpj1kQ1Dp6iMx5PRDTMAdO+H+rqYd2OrNucMl1lYZMq5uDYFc8fFt201jEkUXrPmwk5PnxSFev/pX3aEhYJo2kpk4Gwyup41Nm3u9dP0nYXu1whMyfxvMWKCLTgif41Y4Tg2QWapgaj2+PwyAlBAoNPa9sqR+uCKxXydwUnvqp9MARbsId0bc+p8Yixb/3Zl9Zp90Itf4VmDhTCoe2wxUogIM7wkTpXDwPFktVYGmy/q5TELCTJRayt/Vz9IvlA+DW0xXsRP3JSKxppescPQMtvUxzf3Zs02bf0rfIQ4w0+dNoSF0aNDyXiHadIVMQJvtf//SG3ggFlVRVUdsIUi4If0ZxhrTvD440O0YRij7nJdO5FqxIiWTF1MUNOzarvMtpPBv5sDEaW0qlg8PYg7D+lamgAnLo8zm3e3H0ZWUyc1gQo8GTzZmHgSCPVcDRe8rJ3FIYMEx4DyZVeV1ZTVAFuEOWEiZ0dEhLiWsDo39ZA1eIOcPEMQ8eBOijEvfnb+cujYLebwIonw58+L75hy9I4oF2O/F9pJ2flrPhtgTjFNYdFPr/5RHnUT6l4oWiDNfmmepak/pCBQzfr17U0rX88cZM2MWdDZTf52wOoNTzbHqrE8SJUvgaHiPXQ==
    DB_USER: AgBdPfVYjHlEudQzrSHgrj4jSpNhBJgoiYmwWqJvB4JM+7Sunn+x/K8joTPpC4jrvsE0LdFqyjSLA2N05TlnJNFtQnZLx5V70omP7s7IIgx10tIhEDJuYKJmczqjnetqKqsH1qNLlWKj4w0OWXPvCmbIa4jaec9f4b88cRGXK45A1E9ECqFfo+7pcc9pmrwlNK1SJZUBmXBI+7DFZikd4WBWTBsjmJ3RNTwW3f130Mo7iANkSbGpYvIuV2xlqVAkx+VK7wonmeVju5GJNj3bD1wY8vsH0gd+jJ4ZlyQ10TqcbejlvtgUQIhAKhlgkqQrnfVESmoqzM2UBqXRcuDrw9AS2eQIbLFQlRRb4KU3PIoNnfFPCPIuyNnBA5v00bqNzBG/yd/RZdx0avygzTL5FUl7QNARKT9zkNQe+9VjdZmU3b9WEsiy46ZytMhRh60TOW1UViWN67vaXX/GxglRadJQ051OTrQxrJOH1RaBFMvKuWxhOfxRaZwrqybUVK9dO3RkUHUXHRO0en7771ZNJGJ0OrIKARhM6gUIx8pdDrRIHnYKvXRbNA/QCuzaHI1/qHyYzB/y9rosob7r0OD8hMoxDW3Cg9R5te70ITyctLp6L7c1Oj2hGPitMuizGqRavs5rhJMxNiSEyO3yrBiW9rh0Vzw9/Ej70eshKCGj8JLIC+yqYYNA8VngeykeSkqTO5aLlcoHtUc=
  template:
    metadata:
      name: cronjob-resumen
      namespace: sa-p8-prod
