---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-heartbeat
  namespace: sa-p8-prod
spec:
  encryptedData:
    DB_PASSWORD: AgANlvLrOAC5C9qJQ2g9duTe1q0EX+BoGKEFJoo/UyGiTanDKXz6fp03Jr/k1k/N7eByUn53dddDUQTQLAmySgLUd5kHXm3VC8TSoHPTbx5Nrk0y86dnKz/MDgzczpXymbJrq3iMXAg4vl30UGSun8zmt2yM0nYkiVv1gacDBjg95aWXT+/ALoqKZIdlcP0x0a1jicTW3NCJk/U2UvI1BBOOIMmUX80epU20tQBbA9N6Jxn7WCAPS+oyxsTvdLDdk1BsRfje4alnqNH6cqPEqU6eYqTrKIVecaq9w8qpf4rYdJ2dHBFc0fr+1Iw1QrCNfTHhAGzA1CXFkQiufJU3WkkvnT2BylEDrVPRcdXrFmdYP9Zy8AwNiJtOtHiT91Mjg/BFNq4IaK4YMpg0w9tw/p+V+Nc8ckiqizFvVk6sLBfhvXJYklMGD505Lu8b5/jhVroHD23eLBMvmYev7lbnLzAxq/x0xq9BtUlQgQEXOaxGebvqXoxGciCHEXm3W7MvwGqKgc30eEzf5tWP569FKLi/ryxV7l0e19K2kB8phBjd7uO4a3kfeqPZ6LqBzwfcQjOh7+XBSBWhq106TmszVGmRiwFldMZLkU0m9qZIi3NH4NiHATNDh1cPzXCFR30HUnM6bcV4FQkxBQUgyUVERPrkPq4zG2gYW4k6dM2eFnf4z1w55U0aP+46LvKgH8WwsDSLIo/VFiBTswSxXDfdbe4fQ2TN6oWb8giHVFLdAHrwaQ==
    DB_USER: AgAkvi+h9SE8GnROqYO+CI7sR1Yn7Xu3WpcXcjCIGs+XNKjqczkFJ/GRwTwysb6bfuECffyfzgmOUswk2YamRxQeOw0odoRXUZrAeTr4nh/+6S3xjogUZsjPFesI2m0I+qrDaFGcF4LaY752Vmkb+lmHhGnhUat4FWslbnJ9l8YRT7L7e3G7Te/b1EbZU3sXKtIipWWKdXkc9rYh5wpgecTApOdLVAg6ynaoAv4FYOdaacDOHFaPlmfFg4bLDDLsBPoZ8Uz1iRB2eLr4wfjFW+KF1SBpGZPeGj9hlA5W43QTF+GOGfSdTjymD03j2effkdiqkpHF4vqtBXd+liPhvc/NX8tvqNDOZFyfKMIp6yX4pRiSM0qILPvdMebLkVlrtyloRFDJs17hsQJLckuOjnSFpjGetORTVLHtxYgEajsAeQTTQVLqSCw7ewqAYbNgGwbsQhyOx5PlE9jUUOdxa94fgxAk/JKN0TFMcTbLUjMVVmsTEjNVwhbEwa4VnZS/F3MuAYHJO05gGvO9Btz5gjVHrZ3iWffkRqkRbmLxBFdDzf4spwzTsqdoMe6W5C4enyuJTnyrd/ACU0DHCb3ATE4H+WxE/HeA9UlfA5/DZJOBWikuDfTXTpj+havmXGt6opy4rzRoGQPx/m5RHBno6WqgiB1DlDNZg9CRGHG4ZdLo50Yj/8QqFuNI5F+vxwum/H2S9ysFzDQ=
  template:
    metadata:
      name: cronjob-heartbeat
      namespace: sa-p8-prod
