---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    password: AgB2XhU3FNTFOc/e4flmWbLI9TfkM/1KvFF7kekDFx2+M7cEJq6Pf1EYa8WLz2fIRhW+G/NvZQYQpykGKk5UCtmO4oBJZNFm25Q7vB0rYUw+EpXMPMaGXOxo0DWsR+bQe9IGjCp2cGkwxtJk095rsBFbFh8pfwvAlq9uE1zwED15paNAOYFrLz7EijyarTFoNc0O4qJt2lDThZ76JSuYi0IFZpL1axPB3vHirg94xZER8Q9IfL6blgs5ITWDwCDVYjrdTVF4x6TVS3m1SU8W+w8Ijzti27fmywDjaNXPkRKxxGerwzsI2u0naxrBmnJ6ef5WfGpcGq5P1xwVYIU+geeJZQqw/O1W8W0BccYKugaw3Bgcl1+JIGMEG1GdG1pTfweguY/lq68E30FCaQhpuA35jPLGnW6219k0TL0Sn3p9Bh7YuhQikAwgJaYL6EYnr7x2nCSfFysVTkTRzx1TJ+fe3zPbV00EbK8s/C9HoJOf4uWVE3kqRnetD3QyUZsgj7agT8vKbmgPjHWdbGGYexgR4O/jFIwF6jp1Y2WUuxgAI8jgT1XBG9x4qh9dpKgkYs3E0+LdGZzrD8gUBDom/TOBw3R8BimiWTqMoMswcAzTTIwlHIy4+trGnilA7ntjOadqB/eok9lnusQbo8p7pphTeIsA8ogYBYbu6Kf2bTmlR5JiP4FvE1WdO5sdw1uvjNdMSYuP6NE224uzr+sdi8pHZrnqS9VWw/KRgQfOKKpxuw==
    postgres-password: AgCkNWl5i4m5859+aFN5pwV/dzvxf/Lb4hpoQ+Ap3ul/kK0MRvB46p5EmMG1vjBS5+JYfOwkokuVKEl0I81HPOcR7pv3iGydGIBP2nkt/JqawsMBu889syR2FIXPeWmxYO/so1cQ39xaJK+eYaIgKYvugqUuHjkxXWa78Zi7eAvMQx6bKY2DshL4LGWV0ku8ubIl87PTcVg7kMNIinDnysT9OSvzzZipg447WcILkIp0q54TSZMiFOLCEHiK77ZBYMUAMwRf/1aC/B+l7PjZ3j0U8g8VhBdaf2EQZxEvoYnVpOQGm8m335JIqgnQUDSllLKnGYNdZWyoR7xBidbd/qhd/Tu2cX9XaOk5pXpJY4v33dBCuz50jhtCVNOXFE4CvAxeqzp8BoqZB76ywj9ISLqgDLNI2zZzDj1h1vooikHadcsYWW5w5vbNk5vjUpdM8ePHSLc6/fW3f49qZppu7g6ilxvJtJRBAQMpJiTqCT12hQabu+ImAagBAJELeg1L5EVSG/SMn7faemndGSjxjTZgeCP3k4tBYhHy9xFmbcEFhcstGxwNU9r0HQPzUMddVmBLtWsbm98MH4rstahlE4ysONedpX85KvyoaVlONwEZwocJ/8TUGFqpv6Nq2PjWlg4XOB7FsAkVwURoJC4XlvJM3691oQgYjnfwJSQ6u4+9PBuk4DKgg8tTOITs1vMmUJw0PNMnunu9I5inkKLgPj58z2+uocUmxIDEcgwXX/Txqg==
  template:
    metadata:
      name: postgres-auth
      namespace: sa-p8-prod
