---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    password: AgB2veBYmDEwJ8T2ungTSXekHhdnHJVbMSjwAOR/IABCvXiIlnWPHbVDZ0eURwJVIBsa/1h9VdGCvC/3cYK/2OszrI0QdvWPD6aYypWkB/Ew/b1Wt5uo5fBYcKsnCvEXGL1XSa1dvZSCORQ3KMj9AdhGl1hlReryL6AxQ5xu8XT1vxK6WYnLC3so3T7bq8QzlUbZZp7IanzZNn0LXjAsl7RacPj8EIcWSyYb+Sxxrki0vYIezqFIq4puU3lIBfJ/8XVcxn7Eb1OoIePjg4wKjM0sIzcMCa2A7Eps11wzunEXU4TKN79OkMZ0LLd/IbmoByB9nmi1vsF8E1QsYQ6gcQsW42CF0OCutzGa/G2dPDapn4veNf8DS6HSlGk9w/06CUwprKdnD/AdBdfTy6DH8O7mHYk+/302ETSGMjW4ilbazLspgYvoXi/Wry3BXGFs37NlMgfRkvhihAvHdJtv9N1LfVZUoPBXZScy2mwXwe+H+A+VskcCRbNQyyGdbRvFQ+hoew4E+NXzo1U913CL56EuZyFD5X1KJQzaKDDMluXAThL5nlK6xH2pYpY2ASRKq3f32GEt/k1sDGnhNHKW2U0itArBKsD0OUGZe87HxCbv1WOo92bpCA2ftl5+CXxLUS8aCHIXKWPOV2bDJIcDwsQxk/Q2C+IQl0/D1vEImLERkkTlPKR3TgBN0KSfBIbsXMJDR5oIhfsRzIoKFcY/kupy+EgGCMfSJG/VLSrJ026qvg==
    postgres-password: AgCwXRUkp6WD1gvYbFhvxd4nolj/GhpZ6863B4tJeu5ooP/M8IuDggStsktJnBw2MCWayXs9fo9eZ5nnbhKA0HS6tXrwKUBuLSmnG+X/zKwTklWoTY0OgOwHv703tRHeqmlELpyGrXoasYZOkq1rY1n02OHETEJuQjRL9O+30N93JQajIoOwtYhJY5Cn4PAH4piYcnYczG+jDFpPiEsV8nrH+FE5UdahoDSwiPS5byxwgk7KScKgLw3rtFGK6H9xdHKQqCSTEgPuWuJQszVeIFNXjcMpzgD8nljTEg2SprphjR0HYRaD7O1CwC+azrpGPKT/x2Yz3IjxCtgjEQ0KHfr8ibTK296dw6gWkZThXnA+IJMHU1cRK786qaM0sH8PX/4NZLdGyAMKh5F1p34OPj58tGqoCSDfoz+qKyKoS/YH79gP9C9UMyLtq19FuSoR7QHf636mwrgL7ifujv86ciG6EOBMZuvl9iEQDyrA0326IKKjzaGgIg9WS/IUNkE2/aAcOBPrCj7o/kFoXYMvRlqMgiR0ybAdylTORAYnNDvG6gyNIfmh0DXjCiUYDf+7dv4ou6BAXzpMYtRQnwDOHX1i4OhZOYt6ERRnPBLNNB7+YUDfm7iwjLlMVSdxYpDwua30fXs/w4Npkz/oJSoebWqIp9iecvQHHl0Cxqu4eAPCc4gwuG9yjSOxa+Z91MCAt7LllaeR3ri/MdobIsAzqpVJjj4nQYNtKBqh33vglXfp0Q==
  template:
    metadata:
      name: postgres-auth
      namespace: sa-p8-prod
